= JRobin to RRDtool Converter

This tool can be used to convert link:http://sourceforge.net/projects/jrobin/[JRobin] time series data into link:http://oss.oetiker.ch/rrdtool/[RRDtool] compatible format.
The tool was build in the link:http://www.opennms.org[OpenNMS Project].

IMPORTANT: It is not possible to convert from different OpenNMS storage strategies like `storeByGroup` and `storeByForeignSource`.
           Make sure you use the same settings as the origin OpenNMS with JRobin.
           It is also *not* possible to change internal RRD data structure i.e. 'RRA' or 'step'.
           The 'RRA' configuration in JRobin and RRDtool *must* be the same.

== Requirements

This tool has the following requirements

* Java 1.7 runtime environment (JRE) as link:http://openjdk.java.net/[OpenJDK] or from link:http://www.oracle.com/technetwork/java/index.html[Oracle]
* RRDtool has to be installed
* Build from source requires Java Development Kit (JDK) and link:http://maven.apache.org/download.cgi[Maven]
* Make sure `mvn`, `java` and `javac` binary are in your search path
* Verify JRE version with `java -version` and Java vompiler version with `javac -version` which should be `>= 1.7`
* *Important*: You need enough additional free disk space for the converter, JRobin files are dumped to XML and reimported into RRDtool.
  You may need up to *16 times* the space of your current JRobin file size.
* This tool does not modify existing JRobin files, anyways make always a backup.

== Build from source

The following steps describe how to build the tool from source.

.Step 1: Checkout the source code
----
git clone https://github.com/opennms-forge/jrobin-to-rrdtool-converter.git
----

.Step 2: Change directory
----
cd jrobin-to-rrdtool-converter
----

.Step 3: Compile and assemble runnable jar
----
mvn clean package assembly:assembly
----

.Step 4: Execute tool as runnable jar
----
cd target
java -jar convertjrb-1.0-SNAPSHOT-jar-with-dependencies.jar
----

== Usage

The converter has one argument with the path to OpenNMS JRobin files and has two additional options.

* `-rrdtool`: Location of the `rrdtool` binary which can be located with `which rrdtool`.
  If this option is not set the default is set to `/usr/local/bin/rrdtool`.
* `-threads`: Number of threads to convert JRobin files into RRDtool format.
  If this option is not set, the default value is `4`.
* `<path/to/jrobin-files>` is the path for the tool to search for existing JRobin files.

The convertion is not destructive for the existing JRobin files.
Subdirectories and file names will be preserved.

IMPORTANT: JRobin files are *not* deleted and still exist.
           The exchange XML data has to be manually cleaned up, e.g. `find . -iname $OPENNMS_HOME/share/rrd/*.xml --exec rm -rf {} \;`.
