---
name: Build JRobin to RRDTool converter
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Compile source without tests
        run: |
          make
      - name: Collect build artifacts
        run: |
          make collect-artifacts
      - name: Persist build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: target/artifacts
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: true
          files: |
            *.tar.gz
            *.sha256
